- id: test
  name: test
  description: Runs test suite.
  entry: cargo test
  language: system
  args: ["--"]
  types: [rust]
  pass_filenames: false
- id: coverage
  name: coverage
  description: Checks code coverage, ignores tests.
  entry: cargo tarpaulin
  language: system
  args: ["--", "--ignore-tests"]
  types: [rust]
  pass_filenames: false
- id: audit
  name: audit
  description: Audits dependencies for security vulnerabilities.
  entry: cargo audit
  language: system
  args: ["--"]
  types: [rust]
  pass_filenames: false
- id: fmt
  name: fmt
  description: Format files with cargo fmt.
  entry: cargo fmt
  language: system
  types: [rust]
  args: ["--"]
- id: cargo-check
  name: cargo check
  description: Check the package for errors.
  entry: cargo check
  language: system
  types: [rust]
  pass_filenames: false
- id: clippy
  name: clippy
  description: Lint rust sources
  entry: cargo clippy
  language: system
  args: ["--", "-D", "warnings"]
  types: [rust]
  pass_filenames: false
-  
